version: 2.1
orbs:
  sbom: manifest-cyber/sbom:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@12.0

filters: &filters
  branches:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  # Create jobs to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - sbom/install:
          version: << pipeline.git.revision >>
workflows:
  test-deploy:
    jobs:
      - command-test:
          filters: *filters
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: manifest-cyber/sbom
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - command-test
          context: <publishing-context> # orb-publishing
          filters: *release-filters
