version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  command-test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - sbom/install:
          version: v0.10.0
          generator: syft
          generator_version: v0.92.0
      - sbom/generate:
          generator: syft
          source: .
          source_name: circleci_test
          source_version: 1.0.0

workflows:
  test-deploy:
    jobs:
      - command-test:
          filters: *filters
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: manifest/sbom
          vcs_type: gh # << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - command-test
          context: <publishing-context>
          filters: *release-filters
